# =============================================================================
# KEYWORD FINDER - CONFIGURACIÓN UNIFICADA
# =============================================================================
# Configuración estándar según especificaciones PR-01
# Un solo origen de verdad: config.yaml → nada hardcodeado

project:
  name: "keyword-intel"
  version: "1.0.0"

run:
  geo: "PE"
  language: "es"
  seeds: ["limpieza de piscina", "mantenimiento piscina"]
  target:
    raw: 2000
    filtered: 400
    clusters: 30

expansion:
  limit_per_seed: 200
  alphabet_soup: true
  modifiers: ["mejor", "precio", "curso", "2025", "lima", "peru"]

sources:
  trends: true
  ads_volume: false
  data_source_priority: ["ads", "trends", "heuristic"]

filters:
  min_score: 45
  max_competition: 0.7
  intent_whitelist: ["transactional", "informational"]

scoring:
  weights:
    relevance: 0.45
    volume: 0.35
    competition: 0.10
    trend: 0.10

ml:
  embeddings:
    enabled: true
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
  clustering:
    algo: "hdbscan"
    min_cluster_size: "auto"
    min_samples: "auto"
  intent_classifier:
    enabled: false
    model: "logreg_tfidf_v1"

io:
  db_path: "data/keywords.db"
  exports_dir: "exports"
  cache_dir: "cache"

logging:
  level: "INFO"
  json: true
  filepath: "logs/run_{run_id}.jsonl"